### ISSUE TITLE
"Generate preview" and "Download" buttons are not working

### ISSUE THREAD

**Issue by CHerSun** [averkij/lingtrain-aligner-editor#64]
Not sure if this is some kind of edge case, triggered by me, or just a problem in the current version, but having alignment done with no pending conflicts - when I go to Create tab and press **"Generate preview"** or **"Download book"** there's no result and an exception in console:

```
03-Jul-21 15:06:36 [ERROR] - 24: Exception on /items/Alex/create/fr/en/89f8ad0e6f154cd1896d34e971153600/preview [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functionsrule.endpoint
  File "./main.py", line 773, in get_book_preview
    paragraphs, delimeters, metas = reader.get_paragraphs_polybook(
  File "/usr/local/lib/python3.8/site-packages/lingtrain_aligner/reader.py", line 180, in get_paragraphs_polybook
    par_info = [(par_id, par_sent_ids_from, par_sent_ids_to)
  File "/usr/local/lib/python3.8/site-packages/lingtrain_aligner/reader.py", line 180, in <listcomp>
    par_info = [(par_id, par_sent_ids_from, par_sent_ids_to)
  File "/usr/local/lib/python3.8/site-packages/lingtrain_aligner/reader.py", line 446, in get_next_paragraph
    tid_min, tid_max = min(json.loads(item[0][3])), max(
ValueError: min() arg is an empty sequence
[pid: 24|app: 0|req: 1591/3777] 172.17.0.1 () {48 vars in 1012 bytes} [Sat Jul  3 15:06:36 2021] POST /items/Alex/create/fr/en/89f8ad0e6f154cd1896d34e971153600/preview => generated 290 bytes in 328 msecs (HTTP/1.1 500) 4 headers in 160 bytes (1 switches on core 0)
172.17.0.1 - - [03/Jul/2021:15:06:36 +0000] "POST /items/Alex/create/fr/en/89f8ad0e6f154cd1896d34e971153600/preview HTTP/1.1" 500 290 "http://localhost/user/Alex/create/fr/en" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" "-"
```

**Comment by averkij** [comment]
Fixed in lingtrain-aligner library.
